import { FurnitureMeta } from './types';

export const FURNITURE_CATALOG: FurnitureMeta[] = [
  // ── Seating ──
  {
    id: 'sofa_01',
    name: 'Classic Sofa',
    category: 'seating',
    style: ['classic', 'traditional'],
    dimensions: { w: 1.57, h: 0.80, d: 0.66 },
    description: 'Compact two-seat sofa with rounded arms, neutral upholstery, traditional silhouette.',
    gltfPath: 'Sofa_01_1k.gltf/Sofa_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.85, max: 1.15 },
  },
  {
    id: 'sofa_02',
    name: 'Modern Sofa',
    category: 'seating',
    style: ['modern', 'minimalist'],
    dimensions: { w: 1.81, h: 0.71, d: 0.81 },
    description: 'Low-profile modern two-seat sofa, clean lines, minimal arms.',
    gltfPath: 'sofa_02_1k.gltf/sofa_02_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.85, max: 1.15 },
  },
  {
    id: 'sofa_03',
    name: 'Large Sectional Sofa',
    category: 'seating',
    style: ['modern', 'contemporary'],
    dimensions: { w: 2.73, h: 1.12, d: 0.93 },
    description: 'Large three-seat sofa with high back, generous cushions, throw pillows.',
    gltfPath: 'sofa_03_1k.gltf/sofa_03_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.75, max: 1.1 },
  },
  {
    id: 'arm_chair_01',
    name: 'Baroque Armchair',
    category: 'seating',
    style: ['baroque', 'classic', 'ornate'],
    dimensions: { w: 0.85, h: 1.07, d: 0.77 },
    description: 'Ornate barrel-back armchair with carved dark wood frame, grey upholstery, cabriole legs.',
    gltfPath: 'ArmChair_01_1k.gltf/ArmChair_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.9, max: 1.1 },
    thumbnailPath: 'ArmChair_01.webp',
  },
  {
    id: 'green_chair_01',
    name: 'Green French Chair',
    category: 'seating',
    style: ['french', 'classic', 'ornate'],
    dimensions: { w: 0.67, h: 1.06, d: 0.66 },
    description: 'French-style open armchair with green velvet upholstery, carved dark wood frame.',
    gltfPath: 'GreenChair_01_1k.gltf/GreenChair_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.9, max: 1.1 },
    thumbnailPath: 'GreenChair_01.webp',
  },
  {
    id: 'mid_century_lounge_chair',
    name: 'Mid-Century Lounge Chair',
    category: 'seating',
    style: ['mid-century', 'modern', 'retro'],
    dimensions: { w: 1.01, h: 1.17, d: 1.19 },
    description: 'Mid-century lounge chair with angled wooden shell, brown leather cushion, swivel base.',
    gltfPath: 'mid_century_lounge_chair_1k.gltf/mid_century_lounge_chair_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.9, max: 1.1 },
    thumbnailPath: 'mid_century_lounge_chair.webp',
  },
  {
    id: 'modern_arm_chair',
    name: 'Modern Armchair',
    category: 'seating',
    style: ['modern', 'scandinavian'],
    dimensions: { w: 0.82, h: 0.87, d: 0.97 },
    description: 'Modern armchair with wooden frame, black leather cushions, clean lines.',
    gltfPath: 'modern_arm_chair_01_1k.gltf/modern_arm_chair_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.9, max: 1.15 },
    thumbnailPath: 'modern_arm_chair_01.webp',
  },
  {
    id: 'rocking_chair',
    name: 'Rocking Chair',
    category: 'seating',
    style: ['traditional', 'rustic', 'country'],
    dimensions: { w: 0.71, h: 0.99, d: 0.83 },
    description: 'Traditional dark wood rocking chair with spindle back and curved rockers.',
    gltfPath: 'Rockingchair_01_1k.gltf/Rockingchair_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.9, max: 1.1 },
    thumbnailPath: 'Rockingchair_01.webp',
  },
  {
    id: 'painted_wooden_chair',
    name: 'Painted Wooden Chair',
    category: 'seating',
    style: ['country', 'farmhouse', 'simple'],
    dimensions: { w: 0.43, h: 0.96, d: 0.54 },
    description: 'Simple white-painted wooden dining chair with spindle back detail.',
    gltfPath: 'painted_wooden_chair_01_1k.gltf/painted_wooden_chair_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.9, max: 1.1 },
    thumbnailPath: 'painted_wooden_chair_01.webp',
  },
  {
    id: 'dining_chair_02',
    name: 'Dining Chair',
    category: 'seating',
    style: ['modern', 'simple'],
    dimensions: { w: 0.43, h: 0.97, d: 0.58 },
    description: 'Simple modern dining chair.',
    gltfPath: 'dining_chair_02_1k.gltf/dining_chair_02_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.9, max: 1.1 },
  },
  {
    id: 'metal_stool',
    name: 'Metal Stool',
    category: 'seating',
    style: ['industrial', 'modern'],
    dimensions: { w: 0.35, h: 0.88, d: 0.35 },
    description: 'Tall metal bar stool with round leather seat, cage-style frame.',
    gltfPath: 'metal_stool_01_1k.gltf/metal_stool_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.85, max: 1.2 },
    thumbnailPath: 'metal_stool_01.webp',
  },

  // ── Tables ──
  {
    id: 'round_wooden_table',
    name: 'Round Wooden Table',
    category: 'table',
    style: ['classic', 'traditional'],
    dimensions: { w: 1.40, h: 1.01, d: 1.40 },
    description: 'Round wooden dining/center table with turned pedestal base, warm wood finish.',
    gltfPath: 'round_wooden_table_01_1k.gltf/round_wooden_table_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.7, max: 1.3 },
  },
  {
    id: 'coffee_table_round',
    name: 'Round Coffee Table',
    category: 'table',
    style: ['modern', 'industrial'],
    dimensions: { w: 1.30, h: 0.49, d: 1.30 },
    description: 'Low round coffee table with marble top and curved black metal legs.',
    gltfPath: 'coffee_table_round_01_1k.gltf/coffee_table_round_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.2 },
    thumbnailPath: 'coffee_table_round_01.webp',
  },
  {
    id: 'modern_coffee_table',
    name: 'Modern Coffee Table',
    category: 'table',
    style: ['modern', 'contemporary'],
    dimensions: { w: 0.60, h: 0.39, d: 1.20 },
    description: 'Rectangular coffee table with stone top and wooden frame legs.',
    gltfPath: 'modern_coffee_table_01_1k.gltf/modern_coffee_table_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.3 },
    thumbnailPath: 'modern_coffee_table_01.webp',
  },
  {
    id: 'wooden_table_02',
    name: 'Wooden Table',
    category: 'table',
    style: ['classic', 'rustic'],
    dimensions: { w: 1.13, h: 0.80, d: 0.71 },
    description: 'Rectangular wooden table with simple legs, natural wood grain.',
    gltfPath: 'wooden_table_02_1k.gltf/wooden_table_02_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.2 },
  },
  {
    id: 'wooden_table_small',
    name: 'Small Wooden Table',
    category: 'table',
    style: ['classic', 'simple'],
    dimensions: { w: 0.30, h: 0.42, d: 0.30 },
    description: 'Small decorative wooden table.',
    gltfPath: 'WoodenTable_02_1k.gltf/WoodenTable_02_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.5 },
  },
  {
    id: 'chinese_tea_table',
    name: 'Chinese Tea Table',
    category: 'table',
    style: ['asian', 'traditional', 'chinese'],
    dimensions: { w: 0.84, h: 0.50, d: 0.84 },
    description: 'Low square tea table with carved apron, dark lacquer finish, Asian design.',
    gltfPath: 'chinese_tea_table_1k.gltf/chinese_tea_table_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.3 },
  },
  {
    id: 'side_table_01',
    name: 'Side Table',
    category: 'table',
    style: ['modern', 'wooden'],
    dimensions: { w: 0.55, h: 0.55, d: 0.45 },
    description: 'Wooden cube side table with two shelves, warm wood finish.',
    gltfPath: 'side_table_01_1k.gltf/side_table_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.2 },
    thumbnailPath: 'side_table_01.webp',
  },
  {
    id: 'side_table_tall',
    name: 'Tall Side Table',
    category: 'table',
    style: ['modern', 'simple'],
    dimensions: { w: 0.38, h: 0.76, d: 0.38 },
    description: 'Tall narrow side table / pedestal.',
    gltfPath: 'side_table_tall_01_1k.gltf/side_table_tall_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.85, max: 1.2 },
  },

  // ── Desks ──
  {
    id: 'metal_office_desk',
    name: 'Metal Office Desk',
    category: 'desk',
    style: ['industrial', 'modern', 'office'],
    dimensions: { w: 0.41, h: 0.16, d: 0.78 },
    description: 'Large industrial metal desk with six drawers, dark grey finish.',
    gltfPath: 'metal_office_desk_1k.gltf/metal_office_desk_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.9, max: 1.2 },
    thumbnailPath: 'metal_office_desk.webp',
  },

  // ── Storage ──
  {
    id: 'classic_console',
    name: 'Classic Console Table',
    category: 'storage',
    style: ['classic', 'traditional', 'elegant'],
    dimensions: { w: 1.54, h: 0.95, d: 0.59 },
    description: 'Ornate console table with carved legs, two drawers, rich wood finish.',
    gltfPath: 'ClassicConsole_01_1k.gltf/ClassicConsole_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.15 },
  },
  {
    id: 'gothic_commode',
    name: 'Gothic Commode',
    category: 'storage',
    style: ['gothic', 'antique', 'ornate'],
    dimensions: { w: 1.20, h: 1.21, d: 0.58 },
    description: 'Tall gothic-style commode with pointed arch panels, dark wood, ornate hardware.',
    gltfPath: 'GothicCommode_01_1k.gltf/GothicCommode_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.85, max: 1.1 },
  },
  {
    id: 'modern_wooden_cabinet',
    name: 'Modern Wooden Cabinet',
    category: 'storage',
    style: ['modern', 'scandinavian', 'minimalist'],
    dimensions: { w: 2.44, h: 0.68, d: 0.52 },
    description: 'Wide low wooden cabinet / sideboard, clean lines, light wood, sliding doors.',
    gltfPath: 'modern_wooden_cabinet_1k.gltf/modern_wooden_cabinet_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.7, max: 1.1 },
  },
  {
    id: 'vintage_wooden_drawer',
    name: 'Vintage Wooden Drawer',
    category: 'storage',
    style: ['vintage', 'rustic'],
    dimensions: { w: 0.86, h: 0.55, d: 0.44 },
    description: 'Small vintage drawer unit with two drawers, aged wood finish, round knobs.',
    gltfPath: 'vintage_wooden_drawer_01_1k.gltf/vintage_wooden_drawer_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.2 },
  },
  {
    id: 'drawer_cabinet',
    name: 'Drawer Cabinet',
    category: 'storage',
    style: ['modern', 'industrial'],
    dimensions: { w: 1.14, h: 1.88, d: 0.49 },
    description: 'Tall drawer cabinet with open shelves on top, wood drawers, black metal frame.',
    gltfPath: 'drawer_cabinet_1k.gltf/drawer_cabinet_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.1 },
    thumbnailPath: 'drawer_cabinet.webp',
  },
  {
    id: 'wooden_display_shelves',
    name: 'Wooden Display Shelves',
    category: 'storage',
    style: ['modern', 'scandinavian'],
    dimensions: { w: 0.37, h: 1.56, d: 1.08 },
    description: 'Tall wooden cube shelf unit, 3x4 grid with three lower bins.',
    gltfPath: 'wooden_display_shelves_01_1k.gltf/wooden_display_shelves_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.1 },
    thumbnailPath: 'wooden_display_shelves_01.webp',
  },
  {
    id: 'steel_frame_shelves_wide',
    name: 'Wide Steel Shelves',
    category: 'storage',
    style: ['industrial', 'modern'],
    dimensions: { w: 1.10, h: 2.14, d: 0.50 },
    description: 'Wide 5-tier bookshelf with black steel frame and wooden shelves.',
    gltfPath: 'steel_frame_shelves_01_1k.gltf/steel_frame_shelves_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.05, max: 0.15 },
    thumbnailPath: 'steel_frame_shelves_01.webp',
  },
  {
    id: 'steel_frame_shelves_narrow',
    name: 'Narrow Steel Shelves',
    category: 'storage',
    style: ['industrial', 'modern'],
    dimensions: { w: 0.59, h: 2.14, d: 0.50 },
    description: 'Narrow 4-tier shelf tower with black steel frame and wooden shelves.',
    gltfPath: 'steel_frame_shelves_02_1k.gltf/steel_frame_shelves_02_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.85, max: 1.1 },
    thumbnailPath: 'steel_frame_shelves_02.webp',
  },

  // ── New uploads ──

  // Seating
  {
    id: 'funky_green_couch',
    name: 'Green Delica Couch',
    category: 'seating',
    style: ['modern', 'sculptural', 'funky'],
    dimensions: { w: 2.20, h: 0.80, d: 0.90 },
    description: 'Sculptural modern two-seat couch in muted green/teal fabric with flowing organic form and light wood legs.',
    gltfPath: 'funky_green_delica_couch_modern/delica_couch.glb',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.15 },
    thumbnailPath: 'funky_green_delica_couch_modern.png',
  },
  {
    id: 'tan_modern_sofa',
    name: 'Tan Modern Sofa',
    category: 'seating',
    style: ['modern', 'minimalist'],
    dimensions: { w: 2.20, h: 0.70, d: 0.85 },
    description: 'Minimalist modern three-seat sofa in off-white/cream fabric with clean boxy lines.',
    gltfPath: 'tan_modern_livingroomsofa/tan_modern_livingroom_sofa_with_wood_support.glb',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.15 },
    thumbnailPath: 'tan_modern_livingroomsofa.png',
  },
  {
    id: 'leather_office_chair',
    name: 'Leather Office Chair',
    category: 'seating',
    style: ['modern', 'office', 'executive'],
    dimensions: { w: 0.65, h: 1.20, d: 0.70 },
    description: 'High-back executive office chair in black leather with padded armrests and wheeled base.',
    gltfPath: 'leather-office-chair-low-polygon-game-ready/office_chair.glb',
    placement: 'floor',
    scaleRange: { min: 0.9, max: 1.1 },
    thumbnailPath: 'leather-office-chair-low-polygon-game-ready.png',
  },

  // Tables
  {
    id: 'woodslab_long_table',
    name: 'Wood Slab Dining Table',
    category: 'table',
    style: ['modern', 'industrial', 'rustic'],
    dimensions: { w: 2.50, h: 0.75, d: 1.00 },
    description: 'Long modern dining/conference table with dark wood slab top and U-shaped concrete base.',
    gltfPath: 'woodslab_concretelegs_modern_long_table/wood_slab_kitchendining_table.glb',
    placement: 'floor',
    scaleRange: { min: 0.7, max: 1.2 },
    thumbnailPath: 'woodslab_concretelegs_modern_long_table.png',
  },
  {
    id: 'modern_dining_set',
    name: 'Modern Dining Set',
    category: 'set',
    style: ['modern', 'contemporary'],
    dimensions: { w: 1.60, h: 0.80, d: 1.00 },
    description: 'Modern dining set with rectangular wood table, four grey upholstered armchairs, and decorative vases.',
    gltfPath: 'modern_diningtable_set_4chairs_woodtable_vase/dining_table_set.glb',
    placement: 'floor',
    scaleRange: { min: 0.7, max: 1.2 },
    thumbnailPath: 'modern_diningtable_set_4chairs_woodtable_vase.png',
  },

  // Desks
  {
    id: 'white_modern_office_desk',
    name: 'White Modern Office Desk',
    category: 'desk',
    style: ['modern', 'stylish', 'minimalist'],
    dimensions: { w: 2.00, h: 0.75, d: 0.70 },
    description: 'Sculptural modern white office desk with flowing arch-shaped base and cantilevered top.',
    gltfPath: 'modern_stylish_whiteofficedesk/modern_office_desk.glb',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.15 },
    thumbnailPath: 'modern_stylish_whiteofficedesk.png',
  },
  {
    id: 'desk_set_complete',
    name: 'Complete Desk Set',
    category: 'set',
    style: ['modern', 'office'],
    dimensions: { w: 1.40, h: 0.80, d: 0.70 },
    description: 'Complete desk set with two-tone desk, brown leather chair, globe lamp, laptop, and framed photos.',
    gltfPath: 'desk_set_chair_table_lamp_bookphotos/desk_set.glb',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.15 },
    thumbnailPath: 'desk_set_chair_table_lamp_bookphotos.png',
  },

  // Storage
  {
    id: 'bamboo_bookcase',
    name: 'Bamboo Bookcase',
    category: 'storage',
    style: ['modern', 'industrial', 'bamboo'],
    dimensions: { w: 1.20, h: 1.80, d: 0.40 },
    description: 'Tall open-back bookcase with black metal frame and bamboo shelves, decorated with vases and books.',
    gltfPath: 'bamboo_blackmetal_openbackbookcase/open_back_bookcase.glb',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.15 },
    thumbnailPath: 'bamboo_blackmetal_openbackbookcase.png',
  },
  {
    id: 'marlowe_media_stand',
    name: 'Marlowe Media Stand',
    category: 'storage',
    style: ['mid-century', 'modern'],
    dimensions: { w: 1.30, h: 0.60, d: 0.45 },
    description: 'Mid-century modern brown wood media console with three drawers and a cabinet door.',
    gltfPath: 'marlowe_brown_media_stand/marlowe_medium_media_stand_low_poly.glb',
    placement: 'floor',
    scaleRange: { min: 0.85, max: 1.15 },
    thumbnailPath: 'marlowe_brown_media_stand.png',
  },

  // Wall decor
  {
    id: 'abstract_painting_1',
    name: 'Abstract Painting (Beige)',
    category: 'decor',
    style: ['abstract', 'modern', 'minimalist'],
    dimensions: { w: 1.20, h: 0.70, d: 0.03 },
    description: 'Wide horizontal abstract painting with muted beige/grey tones and teal accents.',
    gltfPath: 'abstract_painting1/picture_painting_abstract_made_in_vermillion_vr.glb',
    placement: 'wall',
    scaleRange: { min: 0.7, max: 1.3 },
    thumbnailPath: 'abstract_painting1.png',
  },
  {
    id: 'abstract_painting_2',
    name: 'Abstract Painting (Colorful)',
    category: 'decor',
    style: ['abstract', 'bold', 'colorful'],
    dimensions: { w: 0.60, h: 0.80, d: 0.03 },
    description: 'Vertical abstract painting with vivid red, yellow, green, pink, and magenta diagonal brushstrokes.',
    gltfPath: 'abstract_painting2/picture_painting_abstract_bars.glb',
    placement: 'wall',
    scaleRange: { min: 0.7, max: 1.3 },
    thumbnailPath: 'abstract_painting2.png',
  },
  {
    id: 'photo_frame_composition',
    name: 'Photo Frame Gallery',
    category: 'decor',
    style: ['modern', 'gallery'],
    dimensions: { w: 1.20, h: 1.00, d: 0.03 },
    description: 'Gallery wall arrangement of 7 photo frames with botanical prints, moon phases, and artistic photos.',
    gltfPath: 'composition_of_photoframes/composition_of_frames_for_wall_decoration.glb',
    placement: 'wall',
    scaleRange: { min: 0.7, max: 1.3 },
    thumbnailPath: 'composition_of_photoframes.png',
  },
  {
    id: 'cat_photo_string',
    name: 'Cat Photo String',
    category: 'decor',
    style: ['quirky', 'casual', 'cute'],
    dimensions: { w: 2.50, h: 0.15, d: 0.02 },
    description: 'Decorative string garland with small cat photo cards clipped along its length with small lights.',
    gltfPath: 'long_string_catphoto_decoration/wall_cats_picture_decoration__wall_decoration.glb',
    placement: 'wall',
    scaleRange: { min: 0.6, max: 1.2 },
    thumbnailPath: 'long_string_catphoto_decoration.png',
  },
  {
    id: 'bamboo_floating_shelf',
    name: 'Bamboo Floating Shelf',
    category: 'storage',
    style: ['modern', 'industrial', 'bamboo'],
    dimensions: { w: 1.50, h: 0.90, d: 0.25 },
    description: 'Three-tier wall-mounted floating shelf with bamboo planks and black slatted metal dividers.',
    gltfPath: 'bamboo_floating_shelf/floating_shelf.glb',
    placement: 'wall',
    scaleRange: { min: 0.7, max: 1.2 },
    thumbnailPath: 'bamboo_floating_shelf.png',
  },
  {
    id: 'ikea_wall_shelf',
    name: 'IKEA Wall Shelf',
    category: 'storage',
    style: ['simple', 'minimalist', 'ikea'],
    dimensions: { w: 0.80, h: 0.05, d: 0.20 },
    description: 'Simple wall-mounted shelf with black metal bracket supports.',
    gltfPath: 'ikea_fjallbo_wallshelf/ikea_fjallbo_wall_shelf.glb',
    placement: 'wall',
    scaleRange: { min: 0.8, max: 1.3 },
    thumbnailPath: 'ikea_fjallbo_wallshelf.png',
  },

  // Decor (floor/surface)
  {
    id: 'bread_pack',
    name: 'Bread Pack',
    category: 'decor',
    style: ['food', 'rustic', 'kitchen'],
    dimensions: { w: 0.50, h: 0.12, d: 0.30 },
    description: 'Four realistic bread loaves in various shapes — round boule, baguette, scored oval, rustic round.',
    gltfPath: 'free__bread_pack_cs2/scene.gltf',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.5 },
    thumbnailPath: 'free__bread_pack_cs2.png',
  },

  // ── Lighting ──

  // Ceiling lights
  {
    id: 'ceiling_lamp_modern_shapes',
    name: 'Modern Geometric Ceiling Lamp',
    category: 'lighting',
    style: ['modern', 'geometric', 'led'],
    dimensions: { w: 1.20, h: 0.40, d: 0.80 },
    description: 'Set of modern geometric LED ceiling fixtures — rectangular frame and circular ring, suspended by cables.',
    gltfPath: 'ceiling_lamp_set_modern_shapes/ceiling_lamps.glb',
    placement: 'ceiling',
    scaleRange: { min: 0.6, max: 1.3 },
    thumbnailPath: 'ceiling_lamp_set_modern_shapes.png',
    emitsLight: true,
  },
  {
    id: 'ceiling_lamp_silvergold',
    name: 'Silver & Gold Pendant Lamp',
    category: 'lighting',
    style: ['modern', 'elegant'],
    dimensions: { w: 0.35, h: 0.50, d: 0.35 },
    description: 'Pendant lamp with conical silver shade, gold/brass fittings, black ceiling canopy.',
    gltfPath: 'ceiling_lamp_silvergold/lamp_02_lowpoly.glb',
    placement: 'ceiling',
    scaleRange: { min: 0.8, max: 1.3 },
    thumbnailPath: 'ceiling_lamp_silvergold.png',
    emitsLight: true,
  },
  {
    id: 'hanging_led_lamp',
    name: 'LED Square Chandelier',
    category: 'lighting',
    style: ['modern', 'led', 'geometric'],
    dimensions: { w: 0.70, h: 0.60, d: 0.70 },
    description: 'Modern pendant chandelier with three concentric square LED rings at different heights.',
    gltfPath: 'hanging_led_lamp_concentricsquares/hanging_led_lamp.glb',
    placement: 'ceiling',
    scaleRange: { min: 0.7, max: 1.3 },
    thumbnailPath: 'hanging_led_lamp_concentricsquares.png',
    emitsLight: true,
  },

  // Floor lights
  {
    id: 'floor_lamp_gold',
    name: 'Gold Floor Lamp',
    category: 'lighting',
    style: ['industrial', 'brass', 'pharmacy'],
    dimensions: { w: 0.50, h: 1.50, d: 0.50 },
    description: 'Tall brass adjustable floor lamp with cross-base stand, articulated boom arm, and dome shade.',
    gltfPath: 'floor_lamp_gold/a_floor_lamp.glb',
    placement: 'floor',
    scaleRange: { min: 0.85, max: 1.15 },
    thumbnailPath: 'floor_lamp_gold.png',
    emitsLight: true,
  },
  {
    id: 'ikea_floor_lamp',
    name: 'White Floor Lamp',
    category: 'lighting',
    style: ['simple', 'ikea', 'minimalist'],
    dimensions: { w: 0.30, h: 1.50, d: 0.30 },
    description: 'Classic IKEA-style floor lamp with chrome base, thin pole, and white tapered fabric shade.',
    gltfPath: 'plain_white_ikeafloorlamp/ikea_lamp.glb',
    placement: 'floor',
    scaleRange: { min: 0.85, max: 1.15 },
    thumbnailPath: 'plain_white_ikeafloorlamp.png',
    emitsLight: true,
  },
  {
    id: 'lava_lamp',
    name: 'Lava Lamp',
    category: 'lighting',
    style: ['retro', 'funky', 'novelty'],
    dimensions: { w: 0.10, h: 0.40, d: 0.10 },
    description: 'Retro lava lamp with purple translucent body, glowing pink wax blobs, chrome base and cap.',
    gltfPath: 'lavalamp/laval_lamp.glb',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.5 },
    thumbnailPath: 'lavalamp.png',
    emitsLight: true,
  },
  {
    id: 'neon_cactus_lamp',
    name: 'Neon Cactus Lamp',
    category: 'lighting',
    style: ['novelty', 'neon', 'fun'],
    dimensions: { w: 0.15, h: 0.45, d: 0.10 },
    description: 'Novelty neon cactus lamp with green neon tube and pink neon flower on a cylindrical base.',
    gltfPath: 'neon_cactus_lamp/neon_cactus_lamp.glb',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.5 },
    thumbnailPath: 'neon_cactus_lamp.png',
    emitsLight: true,
  },
  {
    id: 'salt_lamp',
    name: 'Salt Lamp',
    category: 'lighting',
    style: ['warm', 'natural', 'cozy'],
    dimensions: { w: 0.15, h: 0.25, d: 0.15 },
    description: 'Himalayan salt lamp — glowing pinkish-orange crystal rock on dark wooden base, warm amber light.',
    gltfPath: 'salt_lamp/salt_lamp.glb',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.5 },
    thumbnailPath: 'salt_lamp.png',
    emitsLight: true,
  },

  // Desk/table lights
  {
    id: 'desk_lamp',
    name: 'Architect Desk Lamp',
    category: 'lighting',
    style: ['classic', 'industrial', 'office'],
    dimensions: { w: 0.20, h: 0.50, d: 0.40 },
    description: 'Classic black articulated architect desk lamp with round base and conical shade.',
    gltfPath: 'desk_lamp/scene.gltf',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.3 },
    thumbnailPath: 'desk_lamp.png',
    emitsLight: true,
  },
  {
    id: 'hotel_desk_lamp',
    name: 'Hotel Desk Lamp',
    category: 'lighting',
    style: ['elegant', 'hotel', 'traditional'],
    dimensions: { w: 0.15, h: 0.40, d: 0.15 },
    description: 'Elegant table lamp with tapered linen shade, dark bronze twisted stem, and round wooden base.',
    gltfPath: 'simple_hotel_desklamp/table_lamp.glb',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.3 },
    thumbnailPath: 'simple_hotel_desklamp.png',
    emitsLight: true,
  },
  {
    id: 'table_lamp_classic',
    name: 'Classic Table Lamp',
    category: 'lighting',
    style: ['classic', 'traditional'],
    dimensions: { w: 0.30, h: 0.50, d: 0.30 },
    description: 'Classic table lamp with black glossy ceramic vase base, wide white shade, and gold trim.',
    gltfPath: 'table_lamp_01/scene.gltf',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.3 },
    thumbnailPath: 'table_lamp_01.png',
    emitsLight: true,
  },
];

export function getFurnitureById(id: string): FurnitureMeta | undefined {
  return FURNITURE_CATALOG.find(f => f.id === id);
}

export function getFurnitureByStyle(style: string): FurnitureMeta[] {
  return FURNITURE_CATALOG.filter(f => f.style.includes(style));
}

export function getFurnitureByCategory(category: FurnitureMeta['category']): FurnitureMeta[] {
  return FURNITURE_CATALOG.filter(f => f.category === category);
}
