import { FurnitureMeta } from './types';

export const FURNITURE_CATALOG: FurnitureMeta[] = [
  // ── Seating ──
  {
    id: 'sofa_01',
    name: 'Classic Sofa',
    category: 'seating',
    style: ['classic', 'traditional'],
    dimensions: { w: 1.57, h: 0.80, d: 0.66 },
    description: 'Compact two-seat sofa with rounded arms, neutral upholstery, traditional silhouette.',
    gltfPath: 'Sofa_01_1k.gltf/Sofa_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.85, max: 1.15 },
  },
  {
    id: 'sofa_02',
    name: 'Modern Sofa',
    category: 'seating',
    style: ['modern', 'minimalist'],
    dimensions: { w: 1.81, h: 0.71, d: 0.81 },
    description: 'Low-profile modern two-seat sofa, clean lines, minimal arms.',
    gltfPath: 'sofa_02_1k.gltf/sofa_02_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.85, max: 1.15 },
  },
  {
    id: 'sofa_03',
    name: 'Large Sectional Sofa',
    category: 'seating',
    style: ['modern', 'contemporary'],
    dimensions: { w: 2.73, h: 1.12, d: 0.93 },
    description: 'Large three-seat sofa with high back, generous cushions, throw pillows.',
    gltfPath: 'sofa_03_1k.gltf/sofa_03_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.75, max: 1.1 },
  },
  {
    id: 'arm_chair_01',
    name: 'Baroque Armchair',
    category: 'seating',
    style: ['baroque', 'classic', 'ornate'],
    dimensions: { w: 0.85, h: 1.07, d: 0.77 },
    description: 'Ornate barrel-back armchair with carved dark wood frame, grey upholstery, cabriole legs.',
    gltfPath: 'ArmChair_01_1k.gltf/ArmChair_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.9, max: 1.1 },
    thumbnailPath: 'ArmChair_01.webp',
  },
  {
    id: 'green_chair_01',
    name: 'Green French Chair',
    category: 'seating',
    style: ['french', 'classic', 'ornate'],
    dimensions: { w: 0.67, h: 1.06, d: 0.66 },
    description: 'French-style open armchair with green velvet upholstery, carved dark wood frame.',
    gltfPath: 'GreenChair_01_1k.gltf/GreenChair_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.9, max: 1.1 },
    thumbnailPath: 'GreenChair_01.webp',
  },
  {
    id: 'mid_century_lounge_chair',
    name: 'Mid-Century Lounge Chair',
    category: 'seating',
    style: ['mid-century', 'modern', 'retro'],
    dimensions: { w: 1.01, h: 1.17, d: 1.19 },
    description: 'Mid-century lounge chair with angled wooden shell, brown leather cushion, swivel base.',
    gltfPath: 'mid_century_lounge_chair_1k.gltf/mid_century_lounge_chair_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.9, max: 1.1 },
    thumbnailPath: 'mid_century_lounge_chair.webp',
  },
  {
    id: 'modern_arm_chair',
    name: 'Modern Armchair',
    category: 'seating',
    style: ['modern', 'scandinavian'],
    dimensions: { w: 0.82, h: 0.87, d: 0.97 },
    description: 'Modern armchair with wooden frame, black leather cushions, clean lines.',
    gltfPath: 'modern_arm_chair_01_1k.gltf/modern_arm_chair_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.9, max: 1.15 },
    thumbnailPath: 'modern_arm_chair_01.webp',
  },
  {
    id: 'rocking_chair',
    name: 'Rocking Chair',
    category: 'seating',
    style: ['traditional', 'rustic', 'country'],
    dimensions: { w: 0.71, h: 0.99, d: 0.83 },
    description: 'Traditional dark wood rocking chair with spindle back and curved rockers.',
    gltfPath: 'Rockingchair_01_1k.gltf/Rockingchair_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.9, max: 1.1 },
    thumbnailPath: 'Rockingchair_01.webp',
  },
  {
    id: 'painted_wooden_chair',
    name: 'Painted Wooden Chair',
    category: 'seating',
    style: ['country', 'farmhouse', 'simple'],
    dimensions: { w: 0.43, h: 0.96, d: 0.54 },
    description: 'Simple white-painted wooden dining chair with spindle back detail.',
    gltfPath: 'painted_wooden_chair_01_1k.gltf/painted_wooden_chair_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.9, max: 1.1 },
    thumbnailPath: 'painted_wooden_chair_01.webp',
  },
  {
    id: 'dining_chair_02',
    name: 'Dining Chair',
    category: 'seating',
    style: ['modern', 'simple'],
    dimensions: { w: 0.43, h: 0.97, d: 0.58 },
    description: 'Simple modern dining chair.',
    gltfPath: 'dining_chair_02_1k.gltf/dining_chair_02_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.9, max: 1.1 },
  },
  {
    id: 'metal_stool',
    name: 'Metal Stool',
    category: 'seating',
    style: ['industrial', 'modern'],
    dimensions: { w: 0.35, h: 0.88, d: 0.35 },
    description: 'Tall metal bar stool with round leather seat, cage-style frame.',
    gltfPath: 'metal_stool_01_1k.gltf/metal_stool_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.85, max: 1.2 },
    thumbnailPath: 'metal_stool_01.webp',
  },

  // ── Tables ──
  {
    id: 'round_wooden_table',
    name: 'Round Wooden Table',
    category: 'table',
    style: ['classic', 'traditional'],
    dimensions: { w: 1.40, h: 1.01, d: 1.40 },
    description: 'Round wooden dining/center table with turned pedestal base, warm wood finish.',
    gltfPath: 'round_wooden_table_01_1k.gltf/round_wooden_table_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.7, max: 1.3 },
  },
  {
    id: 'coffee_table_round',
    name: 'Round Coffee Table',
    category: 'table',
    style: ['modern', 'industrial'],
    dimensions: { w: 1.30, h: 0.49, d: 1.30 },
    description: 'Low round coffee table with marble top and curved black metal legs.',
    gltfPath: 'coffee_table_round_01_1k.gltf/coffee_table_round_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.2 },
    thumbnailPath: 'coffee_table_round_01.webp',
  },
  {
    id: 'modern_coffee_table',
    name: 'Modern Coffee Table',
    category: 'table',
    style: ['modern', 'contemporary'],
    dimensions: { w: 0.60, h: 0.39, d: 1.20 },
    description: 'Rectangular coffee table with stone top and wooden frame legs.',
    gltfPath: 'modern_coffee_table_01_1k.gltf/modern_coffee_table_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.3 },
    thumbnailPath: 'modern_coffee_table_01.webp',
  },
  {
    id: 'wooden_table_02',
    name: 'Wooden Table',
    category: 'table',
    style: ['classic', 'rustic'],
    dimensions: { w: 1.13, h: 0.80, d: 0.71 },
    description: 'Rectangular wooden table with simple legs, natural wood grain.',
    gltfPath: 'wooden_table_02_1k.gltf/wooden_table_02_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.2 },
  },
  {
    id: 'wooden_table_small',
    name: 'Small Wooden Table',
    category: 'table',
    style: ['classic', 'simple'],
    dimensions: { w: 0.30, h: 0.42, d: 0.30 },
    description: 'Small decorative wooden table.',
    gltfPath: 'WoodenTable_02_1k.gltf/WoodenTable_02_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.5 },
  },
  {
    id: 'chinese_tea_table',
    name: 'Chinese Tea Table',
    category: 'table',
    style: ['asian', 'traditional', 'chinese'],
    dimensions: { w: 0.84, h: 0.50, d: 0.84 },
    description: 'Low square tea table with carved apron, dark lacquer finish, Asian design.',
    gltfPath: 'chinese_tea_table_1k.gltf/chinese_tea_table_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.3 },
  },
  {
    id: 'side_table_01',
    name: 'Side Table',
    category: 'table',
    style: ['modern', 'wooden'],
    dimensions: { w: 0.55, h: 0.55, d: 0.45 },
    description: 'Wooden cube side table with two shelves, warm wood finish.',
    gltfPath: 'side_table_01_1k.gltf/side_table_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.2 },
    thumbnailPath: 'side_table_01.webp',
  },
  {
    id: 'side_table_tall',
    name: 'Tall Side Table',
    category: 'table',
    style: ['modern', 'simple'],
    dimensions: { w: 0.38, h: 0.76, d: 0.38 },
    description: 'Tall narrow side table / pedestal.',
    gltfPath: 'side_table_tall_01_1k.gltf/side_table_tall_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.85, max: 1.2 },
  },

  // ── Desks ──
  {
    id: 'metal_office_desk',
    name: 'Metal Office Desk',
    category: 'desk',
    style: ['industrial', 'modern', 'office'],
    dimensions: { w: 0.41, h: 0.16, d: 0.78 },
    description: 'Large industrial metal desk with six drawers, dark grey finish.',
    gltfPath: 'metal_office_desk_1k.gltf/metal_office_desk_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.9, max: 1.2 },
    thumbnailPath: 'metal_office_desk.webp',
  },

  // ── Storage ──
  {
    id: 'classic_console',
    name: 'Classic Console Table',
    category: 'storage',
    style: ['classic', 'traditional', 'elegant'],
    dimensions: { w: 1.54, h: 0.95, d: 0.59 },
    description: 'Ornate console table with carved legs, two drawers, rich wood finish.',
    gltfPath: 'ClassicConsole_01_1k.gltf/ClassicConsole_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.15 },
  },
  {
    id: 'gothic_commode',
    name: 'Gothic Commode',
    category: 'storage',
    style: ['gothic', 'antique', 'ornate'],
    dimensions: { w: 1.20, h: 1.21, d: 0.58 },
    description: 'Tall gothic-style commode with pointed arch panels, dark wood, ornate hardware.',
    gltfPath: 'GothicCommode_01_1k.gltf/GothicCommode_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.85, max: 1.1 },
  },
  {
    id: 'modern_wooden_cabinet',
    name: 'Modern Wooden Cabinet',
    category: 'storage',
    style: ['modern', 'scandinavian', 'minimalist'],
    dimensions: { w: 2.44, h: 0.68, d: 0.52 },
    description: 'Wide low wooden cabinet / sideboard, clean lines, light wood, sliding doors.',
    gltfPath: 'modern_wooden_cabinet_1k.gltf/modern_wooden_cabinet_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.7, max: 1.1 },
  },
  {
    id: 'vintage_wooden_drawer',
    name: 'Vintage Wooden Drawer',
    category: 'storage',
    style: ['vintage', 'rustic'],
    dimensions: { w: 0.86, h: 0.55, d: 0.44 },
    description: 'Small vintage drawer unit with two drawers, aged wood finish, round knobs.',
    gltfPath: 'vintage_wooden_drawer_01_1k.gltf/vintage_wooden_drawer_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.2 },
  },
  {
    id: 'drawer_cabinet',
    name: 'Drawer Cabinet',
    category: 'storage',
    style: ['modern', 'industrial'],
    dimensions: { w: 1.14, h: 1.88, d: 0.49 },
    description: 'Tall drawer cabinet with open shelves on top, wood drawers, black metal frame.',
    gltfPath: 'drawer_cabinet_1k.gltf/drawer_cabinet_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.1 },
    thumbnailPath: 'drawer_cabinet.webp',
  },
  {
    id: 'wooden_display_shelves',
    name: 'Wooden Display Shelves',
    category: 'storage',
    style: ['modern', 'scandinavian'],
    dimensions: { w: 0.37, h: 1.56, d: 1.08 },
    description: 'Tall wooden cube shelf unit, 3x4 grid with three lower bins.',
    gltfPath: 'wooden_display_shelves_01_1k.gltf/wooden_display_shelves_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.8, max: 1.1 },
    thumbnailPath: 'wooden_display_shelves_01.webp',
  },
  {
    id: 'steel_frame_shelves_wide',
    name: 'Wide Steel Shelves',
    category: 'storage',
    style: ['industrial', 'modern'],
    dimensions: { w: 1.10, h: 2.14, d: 0.50 },
    description: 'Wide 5-tier bookshelf with black steel frame and wooden shelves.',
    gltfPath: 'steel_frame_shelves_01_1k.gltf/steel_frame_shelves_01_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.05, max: 0.15 },
    thumbnailPath: 'steel_frame_shelves_01.webp',
  },
  {
    id: 'steel_frame_shelves_narrow',
    name: 'Narrow Steel Shelves',
    category: 'storage',
    style: ['industrial', 'modern'],
    dimensions: { w: 0.59, h: 2.14, d: 0.50 },
    description: 'Narrow 4-tier shelf tower with black steel frame and wooden shelves.',
    gltfPath: 'steel_frame_shelves_02_1k.gltf/steel_frame_shelves_02_1k.gltf',
    placement: 'floor',
    scaleRange: { min: 0.85, max: 1.1 },
    thumbnailPath: 'steel_frame_shelves_02.webp',
  },
];

export function getFurnitureById(id: string): FurnitureMeta | undefined {
  return FURNITURE_CATALOG.find(f => f.id === id);
}

export function getFurnitureByStyle(style: string): FurnitureMeta[] {
  return FURNITURE_CATALOG.filter(f => f.style.includes(style));
}

export function getFurnitureByCategory(category: FurnitureMeta['category']): FurnitureMeta[] {
  return FURNITURE_CATALOG.filter(f => f.category === category);
}
